Repository vkamiansky/web-fls-quiz, pull requests merged in 2019-08, with the labels that each got.

#2 Application continues to work when database is unavailable
  src/web-fls-quiz/Controllers/QuestionController.cs
Labels: enhancement

#4 Saving results to database
  src/web-fls-quiz/Controllers/HomeController.cs
  src/web-fls-quiz/Controllers/QuestionController.cs
  src/web-fls-quiz/Controllers/ResultController.cs
  src/web-fls-quiz/Data/DataStorage.cs
  src/web-fls-quiz/Dockerfile
  src/web-fls-quiz/Interfaces/IDataStorage.cs
  src/web-fls-quiz/Interfaces/IQuestionService.cs
  src/web-fls-quiz/Models/QuestionData.cs
  src/web-fls-quiz/Models/QuizInfo.cs
  src/web-fls-quiz/Models/QuizOrganizer.cs
  src/web-fls-quiz/Models/QuizResult.cs
  src/web-fls-quiz/Properties/launchSettings.json
  src/web-fls-quiz/Services/QuestionService.cs
  src/web-fls-quiz/Startup.cs
  src/web-fls-quiz/Views/Home/Index.cshtml
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/components-bundle.js
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/finish/finish.js
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/intro/intro.html
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/intro/intro.js
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/question/question.js
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/submit/submit.js
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/test/test.js
Labels: enhancement

#14 Secure Vault settings configuration mechanism
  src/web-fls-quiz/Controllers/ConfigurationController.cs
  src/web-fls-quiz/Controllers/HomeController.cs
  src/web-fls-quiz/Data/DataStorage.cs
  src/web-fls-quiz/Interfaces/IConfigurationService.cs
  src/web-fls-quiz/Interfaces/IDataStorage.cs
  src/web-fls-quiz/Interfaces/IMailService.cs
  src/web-fls-quiz/Models/Configuration.cs
  src/web-fls-quiz/Models/MailSettings.cs
  src/web-fls-quiz/Models/ProtectedConfiguration.cs
  src/web-fls-quiz/Properties/launchSettings.json
  src/web-fls-quiz/Services/ConfigurationService.cs
  src/web-fls-quiz/Services/MailService.cs
  src/web-fls-quiz/Services/QuestionService.cs
  src/web-fls-quiz/Views/Home/Index.cshtml
Labels: enhancement

#15 Code highlighting
  src/web-fls-quiz/Views/Home/Index.cshtml
  src/web-fls-quiz/Views/Shared/_Layout.cshtml
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/components-bundle.js
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/quiz.app.js
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/quiz.config.js
Labels: enhancement

#16 Added standard images library support
  src/web-fls-quiz/Data/DataStorage.cs
  src/web-fls-quiz/Interfaces/IDataStorage.cs
  src/web-fls-quiz/Models/QuestionData.cs
  src/web-fls-quiz/Models/StandardImage.cs
  src/web-fls-quiz/Services/QuestionService.cs
Labels: enhancement

#23 Code highlighting in questions and case-insensitive quiz name
  src/web-fls-quiz/Controllers/HomeController.cs
  src/web-fls-quiz/Views/Shared/_Layout.cshtml
  src/web-fls-quiz/wwwroot/content/css/shades-of-purple.css
  src/web-fls-quiz/wwwroot/content/css/styles.css
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/components-bundle.js
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/question/question.html
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/quiz.app.js
Labels: enhancement

#26 Fixes and improvements
  src/web-fls-quiz/Controllers/ConfigurationController.cs
  src/web-fls-quiz/Controllers/ResultController.cs
  src/web-fls-quiz/Interfaces/IMailService.cs
  src/web-fls-quiz/Models/QuizInfo.cs
  src/web-fls-quiz/Services/MailService.cs
  src/web-fls-quiz/Views/Home/Index.cshtml
  src/web-fls-quiz/Views/Shared/_Layout.cshtml
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/quiz.app.js
Labels: bug, enhancement

#28 Moved participant mail message data to database
  src/web-fls-quiz/Models/ParticipantMailMessageTemplate.cs
  src/web-fls-quiz/Models/QuizInfo.cs
  src/web-fls-quiz/Services/MailService.cs
Labels: enhancement

#30 CSS Style fixes
  src/web-fls-quiz/wwwroot/content/css/styles.css
Labels: bug

#34 Changed formatting for inline code in questions and answers
  src/web-fls-quiz/wwwroot/content/css/styles.css
Labels: bug

#36 The submit message is changed for upcoming conference.
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/components-bundle.js
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/submit/submit.html
Labels: bug, hotfix

#37 Submit and Finish screen messages are configurable now
  src/web-fls-quiz/Models/QuizInfo.cs
  src/web-fls-quiz/Views/Home/Index.cshtml
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/components-bundle.js
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/finish/finish.html
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/finish/finish.js
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/submit/submit.html
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/submit/submit.js
Labels: enhancement

#39 Fixed: dummy domain is sent in confirmation letter to admin
  src/web-fls-quiz/Services/MailService.cs
  src/web-fls-quiz/Startup.cs
Labels: bug

#38 Added more flexibility to standard images' ID random selection
  src/web-fls-quiz/Data/DataStorage.cs
  src/web-fls-quiz/Interfaces/IDataStorage.cs
  src/web-fls-quiz/Services/QuestionService.cs
Labels: enhancement

#41 All images are configurable now
  src/web-fls-quiz/Controllers/HomeController.cs
  src/web-fls-quiz/Interfaces/IImageService.cs
  src/web-fls-quiz/Models/QuestionData.cs
  src/web-fls-quiz/Models/QuizInfo.cs
  src/web-fls-quiz/Services/ImageService.cs
  src/web-fls-quiz/Services/QuestionService.cs
  src/web-fls-quiz/Startup.cs
  src/web-fls-quiz/Views/Home/Index.cshtml
  src/web-fls-quiz/Views/Shared/_Layout.cshtml
  src/web-fls-quiz/wwwroot/content/css/styles.css
  src/web-fls-quiz/wwwroot/content/images/felix.svg
  src/web-fls-quiz/wwwroot/content/images/finish.png
  src/web-fls-quiz/wwwroot/content/images/fls-logo.svg
  src/web-fls-quiz/wwwroot/content/images/start.png
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/components-bundle.js
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/finish/finish.html
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/finish/finish.js
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/intro/intro.html
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/intro/intro.js
Labels: enhancement

#40 Added bundle maker app.
  appveyor.yml
  src/bundle-maker/BundleMaker.csproj
  src/bundle-maker/Program.cs
Labels: bug, enhancement

#43 Added support for 'number of questions' set on per-quiz basis
  src/web-fls-quiz/Controllers/SettingsController.cs
  src/web-fls-quiz/Models/QuizInfo.cs
  src/web-fls-quiz/Views/Home/Index.cshtml
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/components-bundle.js
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/test/test.js
Labels: enhancement

#45 Added checkboxes support for multiple correct answers
  src/web-fls-quiz/Controllers/QuestionController.cs
  src/web-fls-quiz/Models/Question.cs
  src/web-fls-quiz/Models/QuestionData.cs
  src/web-fls-quiz/Models/UserAnswer.cs
  src/web-fls-quiz/Properties/launchSettings.json
  src/web-fls-quiz/Services/QuestionService.cs
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/components-bundle.js
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/question/question.html
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/components/question/question.js
  src/web-fls-quiz/wwwroot/scripts/apps/quiz/quiz.vm.js
Labels: enhancement

#48 Categorized images in standard images library
  src/web-fls-quiz/Controllers/HomeController.cs
  src/web-fls-quiz/Data/DataStorage.cs
  src/web-fls-quiz/Interfaces/IDataStorage.cs
  src/web-fls-quiz/Models/ImageType.cs
  src/web-fls-quiz/Models/StandardImage.cs
  src/web-fls-quiz/Services/ImageService.cs
Labels: bug, enhancement

#51 Admin email now reads from Vault
  src/web-fls-quiz/Controllers/ConfigurationController.cs
  src/web-fls-quiz/Interfaces/IConfigurationService.cs
  src/web-fls-quiz/Services/ConfigurationService.cs
  src/web-fls-quiz/Services/MailService.cs
Labels: enhancement

#47 Nuke build introduced, bundle maker removed
  .nuke
  appveyor.yml
  build/Build.cs
  build/BundleMaker.cs
  build/_build.csproj
  src/bundle-maker/BundleMaker.csproj
Labels: enhancement
